### ISSUE TITLE
Date Range Resets Itself

### ISSUE THREAD

**Issue by rwschwanke** [ngds/ckanext-ngds#118]
131103-EE
11/7/2013
demo.geothermaldatasystem.org/	
Keyword(s)	Library Feature	Map Feature	Faceted Search	Other	Number of results
contour lines	Yes	No	No	-	17

Notes:  when searching for a new keyword the date range resets itself.

**Comment by ccaudill** [comment]
@smrazgs There is no longer a date range in the Facets search. I think this was a poorly-functioning facet anyway, just due to the metadata. What are your thoughts?

**Comment by smrazgs** [comment]
Date RAnge no longer in UI. Close
