### ISSUE TITLE
Harvest Sources / "Frequency" and "Type" need Tooltips (or something!)

### ISSUE THREAD

**Issue by rwschwanke** [ngds/ckanext-ngds#123]
<http://central.usgin.org/harvest>

The subheadings "Frequency" and "Type" do not have meanings that are obvious to the casual user (bob). Perhaps Tooltips could explain them.

Once explained, please reconsider whether they should be singular or plural.

**Comment by ccaudill** [comment]
this language isn't in new build any longer
