### ISSUE TITLE
Pathway for notifying content providers of bad data

### ISSUE THREAD

**Issue by rclark** [ngds/ckanext-ngds#127]
In a distributed system, we cannot guarantee that the data content that we bring in will be perfect. We also are not building a complex QA/QC mechanism or making any adjustments to data that is harvested.

As a result, we can end up with metadata in the central catalog that is misleading, contains dead links, or are otherwise bad. We will not recognize these errors, but a user of the system might.

In that case, we would like the user to be able to contact the original metadata provider and provide feedback.

- The metadata itself will contain a "maintainer" email address that should be used to contact the owner of the package
- Contacting the package owner should also contact the central node administrator, so that the admin is aware of the bad data in the system and can take any appropriate steps to remedy.
- *Maybe*: The record should be flagged as "under investigation" or something so that other people are made aware of the problem.

**Comment by smrazgs** [comment]
I think the #328, #447, #559, and this are all addressed #559 'report an issue';
