### ISSUE TITLE
Social sharing is missing a header

### ISSUE THREAD

**Issue by mattmackenzie** [ngds/ckanext-ngds#242]
Typically when you have buttons on a website for sharing on social networks, there is some kind of header saying "Share on...".  We don't have that, and for all I know you are just giving me a convenient
![screen shot 2014-01-14 at 10 23 53 am](https://f.cloud.github.com/assets/653087/1911150/b721bff6-7d27-11e3-84e3-8e8136a6ed15.png)
 link to see my funny cat photos.

**Comment by ccaudill** [comment]
now has header
