### ISSUE TITLE
Improve popup messages for harvest source type

### ISSUE THREAD

**Issue by mattmackenzie** [ngds/ckanext-ngds#508]
![screen shot 2014-04-23 at 3 29 20 pm](https://cloud.githubusercontent.com/assets/653087/2781566/40d43900-cb15-11e3-8e03-28972f3b713a.png)

For the CKAN type, maybe change the label to "CKAN/Node In A Box" to make it more clear.

Also, the tooltip delay is a bit slow, not sure if that can be adjusted.

I'd also like to see the tooltip updated to make it clear that for CKAN harvesting, you should only enter the base url of the remote CKAN/NIAB instance.

**Comment by smrazgs** [comment]
This has been cleaned up. Close
