### ISSUE TITLE
WFS/WMS preview not previewing

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#550]
http://geothermaldata.org/dataset/arizona-well-headers/resource/f9e3c577-d2ef-49ec-9af2-a30f2b0988f4
http://geothermaldata.org/dataset/california-well-headers/resource/d49cb083-774f-4206-972c-51c4645f25e3
http://geothermaldata.org/dataset/new-mexico-well-headers/resource/d714b080-25e8-45fc-ad14-73d0e701e56c

Is it a coincidence that the ones not working are served from AZGS?

**Comment by ccaudill** [comment]
Still seems to be an issue:
http://159.87.39.5/dataset/vermont-thermal-conductivity99cc3/resource/665c23db-64e4-4390-b048-003c5414660d

**Comment by smrazgs** [comment]
working now. Close
