### ISSUE TITLE
node landing page link to central aggregator

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-ngds#553]
in text on landing page for out of the box install need to have link for 'search all NGDS' that takes you to the central aggregator.

**Comment by ccaudill** [comment]
We are making decisions about what links need to go into the install. 
Currently, the following tabs do nothing:

Developers
Help
Contact

**Comment by ccaudill** [comment]
These links need to be added into the Footer (and two links in the Header) for CKAN NGDS.

![drupalhomepagelinks2](https://cloud.githubusercontent.com/assets/3188489/6852773/fd9f7ce2-d3a3-11e4-976b-6cd81718b14e.PNG)
![drupalhomepagelinks1](https://cloud.githubusercontent.com/assets/3188489/6852774/fda313f2-d3a3-11e4-8542-d380410b9363.PNG)

**Comment by ccaudill** [comment]
@dan-olaru-reisys Can we put this on the list as those issues that we move to top priority?

Needs to be URLs to the aggregator at http://www.geothermaldata.org/ 

Under the Header:
Developers
Help

Under the Footer:
Under Find & Use Data: Developers, Help, Contact
Under Who We Are:  (all links there as specified above)
Under Learn About NGDS:  (all links there as specified above)

**Comment by smrazgs** [comment]
In the node install, there should be some kind of configuration variable for the root host name for the linked system aggregator, http://geothermaldata.org in our case at this point.  The links from the UI header and footer should append the paths in the comment above to the root path URL from the configuration variable. That way if the aggregator host moves, or if someone is using the nodes in a different system (e.g. the East African Geothermal Data System), its easy to reconfigure for a different aggregator.

**Comment by dan-olaru-reisys** [comment]
this feature has been implemented, please validate @ http://uat-ngds.reisys.com/
I've also updated: https://github.com/ngds/install-and-run/blob/master/README.md

**Comment by ccaudill** [comment]
Excellent! The links look great.
@skmar  Could you take a look and confirm?

**Comment by skmar** [comment]
@ccaudill 
The links look good to me.
