### ISSUE TITLE
Download zipfile resource showing up twice for the same dataset

### ISSUE THREAD

**Issue by jdeprizio** [ngds/ckanext-ngds#565]
geothermaldata.org

Utah Themal Spring Features data resource on Map UI

Download zipfile resource showing up twice for the same dataset. One zip download is for the shapefile while the other is for the excel spread sheet but this difference should be made more obvious? 

I checked other data resources as well i.e. AASG Geothermal Data: Thermal Springs Feature Content Model has 4 “Download Zipfile Resource” options in the Map UI Results list.

**Comment by ccaudill** [comment]
Looks fixed in new build: http://159.87.39.5/dataset/utah-thermal-spring-features
