### ISSUE TITLE
Total results count needed on map search UI

### ISSUE THREAD

**Issue by jdeprizio** [ngds/ckanext-ngds#567]
demo.geothermaldata.org

I like the way the counts of resources are shown on the map for a given area but there should also be a total results count available to the user.

**Comment by ccaudill** [comment]
I cannot test this, as I can't get our current build or REI's to work for text searches

**Comment by smrazgs** [comment]
The result count was displayed in the v1 build; still does in http://www.geothermaldata.org/ngds/map. Is there some way we can get this functionality back?

**Comment by GaryHudmanAZGS** [comment]
Modified mapsearch javscript to perfom counts and display correct #636
