### ISSUE TITLE
facet content disappears on "Show More"

### ISSUE THREAD

**Issue by dscuyle** [ngds/ckanext-ngds#573]
on demo.geothermaldata.org ... If "Show More ..." link is pressed under a facet list the contents of that list disappears (rather than expanding as it should).

**Comment by ccaudill** [comment]
http://159.87.39.5/dataset?q=arizona&sort=score+desc%2C+metadata_modified+desc&_res_format_limit=0&_md_author_names_limit=0&_md_content_models_limit=0

All working in new build.
