### ISSUE TITLE
View ATLAS from NGDS home page

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#585]
@skmar @ridavis 
Geothermal Resources Digital Atlas needs to go on the NGDS site somewhere, per Arlene. Somewhere that people will see it and be interested in it right away. Some ideas:
Maybe under the Geo Analysis Resources
a new tab "Success Stories"
on the rotator
somewhere else on the main page or elsewhere

The wording "Success Stories" was particularly liked, and I think a winner was having a link under Partners, having another link to this under the "Full list of partners" link. Perhaps even better would be a graphic of some kind just to the left of the Partners graphic.

**Comment by ccaudill** [comment]
Please create a new Sucess Stories tab, next to Tools & Applications.

Text for this new page:

------------------------------------------------ 

What is the success of NGDS?  It is in the immense nationwide data compilation and standardization, the ease of access of those data and data products to spur geothermal energy development and research, and in the collective enhancement of NGDS partners technical capability and capacity to continue to produce and disseminate this data  and develop tools for its use.  Highlights of research and development successes from the NGDS partners are outlined in the ATLAS (acronym here?). Research and development continues from private and public industries relying on the resources of the NGDS.

PUT IN THE ATLAS HERE ---------------------

A few examples of NGDS partners who have excelled due to their being a node in this system are quite varied, but a few are highlighted below.

Hawai’I Groundwater & Geothermal Resources Center
See explicit NGDS contributions to the University of Hawai’I at Manoa’s work at various project and historical sites:
http://www.higp.hawaii.edu/hggrc/projects/ 
http://www.higp.hawaii.edu/hggrc/projects/geothermal-digital-collection/ 
http://www.higp.hawaii.edu/hggrc/history/ 
http://www.higp.hawaii.edu/hggrc/about-hggrc/    

The following are websites provided by Shawn Naylor, at the Indiana Geological Survey NGDS node:
Overview of geothermal resources: http://igs.indiana.edu/Geothermal/
Ground source heat pumps and geology in Indiana: http://igs.indiana.edu/Geothermal/HeatPumps.cfm
The Indiana Shallow Geothermal Monitoring Network: http://igs.indiana.edu/Geothermal/ShallowGeothermal.cfm
Downloads of IN contributions to NGDS: http://igs.indiana.edu/Geothermal/Resources.cfm

See the Tools & Applications page to view various Web Map Applications built by NGDS partners, which grew from and supports this effort but has also expanded to fit the goals and needs of the given nodes.

**Comment by skmar** [comment]
This page has been added as a menu item, but I did not link the Atlas yet, because it still needs a new cover.
http://geothermaldata.org/success-stories

**Comment by ccaudill** [comment]
@rdavis Do you know when this will get a new cover?

**Comment by ridavis** [comment]
Stephanie plans to work on it later today.

**Comment by ccaudill** [comment]
Thanks @ridavis Wjat are your thoughts on a short sentence to tell the reader what the Atlas is, maybe how it came about?

**Comment by ridavis** [comment]
Good idea. Did you mean as part of the cover or as part of the description on the website? 

NGDS Atlas: An illustrated guide to the maps, data, and online applications contributed to the NGDS by the state surveys.

**Comment by ccaudill** [comment]
Thanks! I just wanted a bit for the site text - this is great.

**Comment by ccaudill** [comment]
Nicely done all. http://testportal.geothermaldata.org/success-stories
We'll close this issue when I confirm tomorrow that Arlene likes where we've put it.

**Comment by skmar** [comment]
The latest version of the Atlas has been added to the Success Stories. Let me know if you want ant edits.
http://testportal.geothermaldata.org/success-stories

**Comment by ccaudill** [comment]
seriously, great job on that @skmar @ridavis  :)

**Comment by ridavis** [comment]
Thank you! New cover looks great, Steph. I noticed a couple minor grammatical errors in the text: 

1) Sentence 1 - " and in the collective enhancement of NGDS partners technical capability and capacity to continue to produce and disseminate this data and develop tools for its use."  should be 

" NGDS partners' technical capability.."

2) Last sentence: "See the Tools & Applications pages to view various Web Map Applications built by NGDS partners, which grew from and supports this effort but has also expanded to fit the goals and needs of the given nodes."  should be: 

"which grew from and support this effort, but have expanded to meet the goals of individual nodes."

**Comment by ccaudill** [comment]
Go for it - please make any changes you see necessary. Thanks!

**Comment by ridavis** [comment]
Will do.

**Comment by ccaudill** [comment]
Arlene and Dave are reviewing - let's wait for comment then close the task

**Comment by ccaudill** [comment]
@ridavis There was one thing that Arlene commented about regarding the Atlas - she had in mind that it was going to be more interactive... we did not know that somehow, and to make an online app would be hugely time-consuming (though not impossible for the future). For now, I suggested that we might be able to embed hyperlinks in the slides, where each state slide links to the tracking map where users can tool around and look at each state's contributions

**Comment by ridavis** [comment]
Wow.... well, we're not working with slides, It's a PDF. We have embedded hyperlinks in the text, I am not sure how to embed hyperlinks in the map images but I assume it can be done without much trouble... some can lead to the WFS hosted by the individual states, some to their online static maps, and possibly some can lead to the NGDS..... That will take at least several hours, though. Some of the links need to be totally recreated because I just took screenshots of the WFS.

**Comment by ccaudill** [comment]
PDF pages is what I meant... I was thinking about just linking each state's page to the http://repository.stategeothermaldata.org/track/map/ but I can't seem to access it right now

**Comment by ridavis** [comment]
If Arlene would be happy with that, I would be happy with that.

**Comment by ccaudill** [comment]
What about just this link http://www.stategeothermaldata.org/content/interactive_data_contribution_map wherever you see the flower icon (which is on every state's page)??

**Comment by ridavis** [comment]
If Arlene doesn't have a problem with it I'm happy to do that, but I am hesitant because Diane said that the figures visible on this map are not accurate representations of a state's actual data contributions. IN fact, she painstakingly went back through all the data to correct our numbers because we had initially pulled data from the stategeothermal.org map. I know she was uncomfortable showing the data tracking map to the public because it was used as an internal tool. Have the numbers on this been updated recently?

**Comment by ccaudill** [comment]
no, they haven't. I don't know why Diane's numbers were different than what were on here. That's a bummer

**Comment by smrazgs** [comment]
@ccaudill  as far as I can tell the original issue is resolved; if there are other issues in this thread that are not resolved, can you create separate issues.
