### ISSUE TITLE
hard drive back-up of NGDS v1 data snapshot

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#586]
Need hard drive of data capture - Arlene said that she's still waiting to hear from Steve on that
@smrazgs

**Comment by ccaudill** [comment]
during our last Sandia call, Arlene said she was waiting to hear about the drive for data capture - should we ask Ron where that initial dump is in-house? Then maybe ping Adrian on that process? We can try it from https://github.com/ngds/data-archiver though it indicates data to be dumped in an EC3

**Comment by smrazgs** [comment]
Ron copied the archive from S3 to a hard drive and it was overnighted-yesterday. closing
