### ISSUE TITLE
Separate Tools and Applications into 2 different tabs

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#587]
Per Arlene and Dave:
The focus here should be distinct and separated:  One group we need to target is the geothermal developers. The other group we need to target is the GIS user. Therefore, we should make 2 tabs here, keeping largely the text already at Tools and Applications under and rename the tab "GIS Resources". It should have the Data Explorer more prominent and have more text about the Geothermal Prospector. This should be for the everyday user and for the more GIS-techy.
The second tab "Geothermal Analysis Resources" is for geothermal developers specifically - GeoFrat, Geothermal Prospector, Reservior modeling, Play Fairways Analysis (tool and techniques from those teams).
@skmar @ridavis

**Comment by ccaudill** [comment]
splitting the Tools & Apps up…. could we do a drop down from this ‘tab’?  Perhaps which separates this into two different pages, one called GIS Resources and the other called Geothermal Analysis Resources.

Text for Geothermal Analysis Resources page:  
  
  
Tools and techniques for geothermal development are quickly being built to best utilize the resources provided by NGDS.  The Play Fairways Analysis teams are working on novel exploration and development analyses specifically with NGDS data, and those various grant products will be showcased here for disseminated use upon completion of those projects.

Current tools and resources with which NGDS is compatible can be found below:

Geothermal Exploration
The following tools and resources can be used to facilitate your geothermal exploration.
•	NREL Geothermal Prospector: A Web-accessible mapping tool developed for the geothermal power industry. This tool is designed to provide easy access to geothermal resource datasets and other data relevant to utility-scale geothermal power projects. Geothermal Prospector can load NGDS Web Map Services (WMS) and Web Feature Services (WFS) to facilitate exploration - e.g., Reservoir models.
•	NGDS Data Explorer: A Web application designed to load and display NGDS WFS from a text or location search. When a WFS has been loaded, a user can then export attributes (standardized data) from this service as an HTML table, CSV file, or Microsoft Excel workbook. Please note that the user can load more than one WFS at a time.

Financial
The following tools, models, and resources can be used to predict and provide information about the costs of geothermal development.
•	GeoFRAT: Geothermal Financial Risk Classification and Assessment Tool (GeoFRAT) is an NGDS application that helps users assess the resource potential and financial risks that may be associated with producing electricity from a given geothermal resource. When used in conjunction with other widgets and tools such as GETEM, GeoFRAT can help you conduct detailed risk analysis for a geothermal resource development project.
•	Geothermal Electricity Technology Evaluation Model (GETEM): This tool models the estimated performance and costs of currently available U.S. geothermal power systems. GETEM can analyze and evaluate currently available technologies and estimate the cost of certain technologies five to 20 years in the future. The model is intended to help the Geothermal Technologies Office (GTO) determine which proposed RD&D programs and projects offer the greatest prospective return on investment (ROI).

Geographic Information Systems (GIS) and Data Applications

These Web, desktop, and GIS software applications can be used to access, explore, visualize, and analyze NGDS data.
•	NREL Geothermal Prospector - http://maps.nrel.gov/gt_prospector 
•	GETEM, DOE Geothermal Technologies Office - http://www1.eere.energy.gov/geothermal/getem.html

**Comment by skmar** [comment]
New pages and a drop down menus were created.

GIS Resources:
http://geothermaldata.org/tools-applications/gis-resources

Geothermal Analysis Resources:
http://geothermaldata.org/tools-applications/geothermal-analysis-resources) page has been created with the text above, with the Data Explorer and  Geothermal Prospector are more prominent

I did not include the text below because the links are already included in the text, it seems redundant to me.

>Geographic Information Systems (GIS) and Data Applications
>
>These Web, desktop, and GIS software applications can be used to access, explore, visualize, and >analyze NGDS data.
>• NREL Geothermal Prospector - http://maps.nrel.gov/gt_prospector 
>• GETEM, DOE Geothermal Technologies Office - >http://www1.eere.energy.gov/geothermal/getem.html

**Comment by ccaudill** [comment]
On the Success Stories page, can you make a "Indiana Geological Survey Geothermal Information" heading after the HA section? And can you make some space between the ATLAS section and the HA section? @skmar

**Comment by ccaudill** [comment]
@skmar Can you make "GIS Resources" a larger, separated heading as it is the page heading?

**Comment by ccaudill** [comment]
great job steph!

**Comment by skmar** [comment]
@ccaudill I've made all the page headings larger and in capitals to separate them out from the rest of the page. Let me know what you think.

**Comment by ccaudill** [comment]
yep, much better! thanks!

**Comment by ccaudill** [comment]
@skmar I'm wondering if it will work in this site (design-wise) if I found icons for you for all the GIS apps. Do you think we could put small icons in and it still flow the same and not look crowded?

**Comment by skmar** [comment]
Take a look at the page, I had some of the icons available and put a few in.

The icons work for the GIS apps that have descriptions, but for the ones without descriptions it’ll take a little more work to get them to look good.

What do you think?

**Comment by ccaudill** [comment]
I see that under GIS Software the formatting is messed up (at least in FireFox), but the stuff under "Free and Open-Source GIS Software to view NGDS data" I really like!!

**Comment by skmar** [comment]
@ccaudill 
I found logos for most of the applications. The names below are ones that don't really have a clear idea what to use as the logo. Christy, you have a better understanding about the applications can you help me find the best logo to use for these applications?

MapInfo 8.5
Manifold
Global Mapper v. 9.0
GAIA
ERDAS Imagine
Bentley Microstation V8i
GeoScene 3D

**Comment by ccaudill** [comment]
are you putting the logos somewhere on the server?

**Comment by skmar** [comment]
Generally I’ve been putting graphics for the NGDS website in the AZGS GeoExtension GRAPHICS folder (this where I keep most graphic related work).

Here’s the path for the GIS Resource logos folder:

\\COVELLITE\LibraryAndOutreach\AZGS GeoExtension GRAPHICS\National-Geothermal-Data-Systems\website-graphics\GIS Resources page logos

--Stephanie

**Comment by ccaudill** [comment]
I would remove ERDAS Imagine - I don't know anything about it, and I can't quite sort out if it is GIS or what from their suite is actually appropriate to list here.  Also, I couldn't find an image for GeoScene that was big enough...

**Comment by skmar** [comment]
I took out ERDAS Imagine.
Would the IGIS logo work for GeoScene?
![igis_logo](https://cloud.githubusercontent.com/assets/6004822/6362274/9f79a5a6-bc48-11e4-937f-036d2c69e96e.png)

**Comment by ccaudill** [comment]
yep, that will work

**Comment by skmar** [comment]
The latest logo is in.

Let me know if you want any changes.

**Comment by ccaudill** [comment]
can you remind me what Pam's latest URL to that live site is?

**Comment by skmar** [comment]
http://geothermaldata.org/tools-applications/gis-resources

**Comment by ccaudill** [comment]
@pjbarry21

**Comment by skmar** [comment]
http://testportal.geothermaldata.org/tools-applications/gis-resources

**Comment by ccaudill** [comment]
thanks!

**Comment by ccaudill** [comment]
Nicely done @skmar  I think we can close this issue now

**Comment by ccaudill** [comment]
Arlene and Dave are reviewing - let's wait for comment then close the task
