### ISSUE TITLE
Filters/Values are not showing for content model facet on QA

### ISSUE THREAD

**Issue by sbalmuri-rei** [ngds/ckanext-ngds#589]
Filters/values are not showing for content model facet when the values are selected in the content model drop down while creating a dataset.

![contentmodelfilter](https://cloud.githubusercontent.com/assets/8029135/5477382/d84bd09c-85f8-11e4-9948-c4954d13556c.png)

**Comment by ccaudill** [comment]
working properly in new build: http://159.87.39.5/dataset?q=arizona&sort=score+desc%2C+metadata_modified+desc
