### ISSUE TITLE
Additional Information section shows the harvester information if the metadata and author fields are left blank,Is this expected

### ISSUE THREAD

**Issue by sbalmuri-rei** [ngds/ckanext-ngds#591]
Additional Information section shows the harvester information if the metadata and author fields are left blank,Is this expected

![metdatavalues](https://cloud.githubusercontent.com/assets/8029135/5477592/a60cda52-85fa-11e4-9ea8-2fdb441573ef.png)

**Comment by ccaudill** [comment]
this has been fixed, and looks great:

![ckan-image](https://cloud.githubusercontent.com/assets/3188489/6191881/3f87a3e6-b36a-11e4-8602-dd68b5fef48c.PNG)
