### ISSUE TITLE
For the datasets which are created with USGIN "Yes",when we edit these datasets content model layer information is not shown

### ISSUE THREAD

**Issue by sbalmuri-rei** [ngds/ckanext-ngds#592]
For the datasets which are created with USGIN "Yes",when we edit these datasets content model layer information is not shown

![editusigyes](https://cloud.githubusercontent.com/assets/8029135/5477626/f7866b82-85fa-11e4-980e-36b993f9936a.png)

**Comment by ccaudill** [comment]
When you edit a record (go into Manage and Edit), it appears this was fixed:

![ckan-manage](https://cloud.githubusercontent.com/assets/3188489/6191987/fcb1ac3c-b36a-11e4-929f-f7ba24672e13.PNG)
