### ISSUE TITLE
Internal Server Error/Server error is thrown when dataset set is created with USGIN Yes and Author,metadata information is given

### ISSUE THREAD

**Issue by sbalmuri-rei** [ngds/ckanext-ngds#595]
Internal Server Error/Server error is thrown when dataset set is created with USGIN Yes and Author,metadata information is given.

![servererror](https://cloud.githubusercontent.com/assets/8029135/5510228/ebdf5642-878d-11e4-8905-1d76ab041b7c.png)

**Comment by ccaudill** [comment]
@sbalmuri-rei Could you clarify on how this error might be reproduced?

**Comment by ccaudill** [comment]
I understand - when publishing the data. I successfully added a record with the author and metadata information. Looks like this have been fixed in new build.
