### ISSUE TITLE
Expected filters/facets on the data page

### ISSUE THREAD

**Issue by sbalmuri-rei** [ngds/ckanext-ngds#598]
Expected filters/facets on the data page:

Are we suuposed to have metadata contact, Public/Private and category filters/facets on the data page of NGDS systems

This scrrenshot is from geothermal
![filters](https://cloud.githubusercontent.com/assets/8029135/5531652/5877a8c0-89fc-11e4-89de-b2d04df0e7c5.png)

**Comment by ccaudill** [comment]
looks great in new build: http://159.87.39.5/dataset
