### ISSUE TITLE
pyCSW needs to be part of installation stack

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-ngds#599]
http://uat-ngds.reisys.com/csw should get the CSW endpoint for the NGDS CKAN node. (e.g. http://www.geothermaldata.org/csw). What am I missing to access the CSW service? (trying to harvest into the prototype production node at http://159.87.39.5

**Comment by ccaudill** [comment]
https://github.com/ngds/install-and-run/issues/22
