### ISSUE TITLE
ckan_harvester errors

### ISSUE THREAD

**Issue by jessica-azgs** [ngds/ckanext-ngds#600]
Since pyCSW is not integrated yet attempted to harvest directly from the GINStack node instances with the plugin `ckan_harvester`. Only a few packages harvested because most have tags which contain invalid characters like : and &. An example error:

```
Invalid package with GUID 63d9d995-a373-4032-830a-2c18dda7c42e: {'tags': [u'Tag "usginres:collection:dataset" must be alphanumeric characters or symbols: -_.']}
```

Once pyCSW is integrated we won't need to harvest using ckan_harvester so not attempting to fix at this time but wanted to make note of the error.

**Comment by ccaudill** [comment]
https://github.com/ngds/install-and-run/issues/22
