### ISSUE TITLE
Add some state map apps to Tools & Apps page

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#601]
Add:

Arizona Oil and Gas Wells Viewer	http://welldata.azogcc.az.gov/

OH DNR Web Map Services Homepage	http://geosurvey.ohiodnr.gov/energy-resources/geothermal-energy/geothermal-gis-services

CA Division of Oil, Gas, and Geothermal Resources Well Finder	http://maps.conservation.ca.gov/doggr/index.html

**Comment by skmar** [comment]
This was added to the new Geothermal Analysis Resources page:
http://geothermaldata.org/tools-applications/geothermal-analysis-resources

Let me know if you prefer it on the GIS Resources page instead.

**Comment by ccaudill** [comment]
thanks Steph!
