### ISSUE TITLE
 GDR-NGDS integration

### ISSUE THREAD

**Issue by ykhadilkar-rei** [ngds/ckanext-ngds#610]
Some background 
1.  Here's the part of the USGIN harvester which extends the vanilla CKAN CSW harvester: https://github.com/ngds/ckanext-metadata/blob/master/ckanext/harvest/usgin.py#L96.  This function has a look through each individual harvested metadata record and pulls out the parts of interest.  Off the top of my head, here is where I'd throw a hook in to pull out those CSV file URLs and start working with them.
 
2.  Here's your validation service, the venerable USGIN Models API: https://github.com/usgin/usginmodels.  This is what you'd use for validation.
 
3.  Now there's two ways you can deploy the CSV file through Geoserver.  The way that makes most sense would be to use CKAN's DataPusher software.  NGDS CKAN should already deploy with it.  You'd probably need to hook directly into this function: https://github.com/ckan/datapusher/blob/115d3fe33c1a9041e17a964a3eda9afe72f82437/datapusher/jobs.py#L250 and it would take care of everything for you.  If you don't care about storing the contents of the CSV in the database, then use GDAL/OGR to make a VRT of the CSV and feed it to Geoserver instead of using the DataPusher.
 
4.  Then you'd use https://github.com/ngds/ckanext-geoserver to publish the OGC services you want.
With all that laid out, this task looks like it's more about chaining together a bunch of existing processes than writing new software.  There's probably multiple ways to do it, but here's two ways I can think of off the top of my head:
For both scenarios, you're probably going to want to use the DataPusher function mentioned in item #3 above.  You're going to want to alter it so that it returns a success/failure value because your going to have to implement it with or as a dependency injection.  To implement it as a dependency injection, it'll be passed as a parameter into another function that handles storing the CSV in the database and publishing to Geoserver.  Alternatively, to implement it with a dependency injection you'd pass the publish to Geoserver function in as the dependency injection to inverse the flow.  The reason inversion of control is necessary here is because the program needs to listen for the DataPusher process to finish.  Normally, it operates asynchronously but it's going to need to run as a blocking process.  However you want to implement it, I'll refer to this process as "ComplicatedProcess".
 
The easy way:
Extend https://github.com/ngds/ckanext-metadata to support the new functionality.  Specifically, add a bunch more private functions to this object: https://github.com/ngds/ckanext-metadata/blob/master/ckanext/harvest/usgin.py#L11.  Ultra-pseudo-code:
-- If string scraped from metadata is CSV, download CSV.
-- If CSV downloads, the entire harvest process gets put on hold and we start this new process.  Else log the error and continue the harvest as usual.
-- Feed CSV to USGIN Models API for validation
-- If validation passes, pass the CSV to "ComplicatedProcess" and wait for return.  If success, enter new metadata entry.  Else, pass and return back to regular harvest process.
This would be the easiest way to implement the logic, but you'd be taking a tremendous performance hit.  Everything would run in a blocking event loop and if a harvest contains a lot of CSVs to be harvested you could expect the whole harvest to take at least twice as long, probably longer.
The sexy, elegant way:
You'd do everything as mentioned in the easy way except you'd use a framework like twisted (https://twistedmatrix.com/trac/) or tornado (http://www.tornadoweb.org/en/stable/) to create an asynchronous, non-blocking pool of processes to minimize the performance hit.

**Comment by ykhadilkar-rei** [comment]
@ccaudill we can track progress and communication here. I hope thats ok.

**Comment by ykhadilkar-rei** [comment]
@ydave-reisys Please add your questions here

**Comment by ydave-reisys** [comment]
@ccaudill  I had following question regarding identifying if dataset confirms with USGIN content model schemas:
 
For e.g. considering this dataset: http://159.87.39.4/dataset/michigan-well-log-observation-data

I don't see any information regarding model, version and layer except keyword usgincm:well log observation in metadata xml (http://159.87.39.4/metadata/iso-19139/3cbd7ec9-1bbe-4068-a218-0ca0cf326a4a.xml)

Can you please advise what should we look for in metadata to confirm if dataset belongs to which Model, Version and Layer.  We need this information to validate CSV as well.

**Comment by ccaudill** [comment]
Exactly - the only indications of which content model will be by keyword, which was why this was a big deal to us https://github.com/ngds/ckanext-ngds/issues/609
That is a good point about the version and layer ... @ydave-reisys  For the version - I think we can assume that the latest version of the content model is being used. That way, if it is not, the validation fails and the user must put the data in the newest version before it can be published. @smrazgs Could you comment?
As for the layer, what would be the best way to approach this from a programmatic prospective? Should we add keywords that are specific to a layer, for those services that have multiple layers?

**Comment by ccaudill** [comment]
The file at http://159.87.39.4/dataset/michigan-well-log-observation-data did not conform to the schema, but I don't think that's a problem for you here. It was harvested in with a WFS and a WMS, so it will not need to be considered for the publication process, as it has already been published. This is important - it's not all CSV files, but only those CSV files which do not have distribution:
<gmd:transferOptions>
<gmd:MD_DigitalTransferOptions id="distribution-37cc87f7-89fd-49c2-8241-23efdc54e6e6"><gmd:onLine>
<gmd:CI_OnlineResource>
<gmd:linkage>
<gmd:URL>http://mgs.geology.wmich.edu/arcgis/services/MIWellLogs/MapServer/WMSServer?request=GetCapabilities&service=WMS

This file was an Excel and not a CSV anyway.

Was there another reason you were asking about that particular dataset?

**Comment by ydave-reisys** [comment]
@ccaudill : Thanks for explanation.. this helps a lot! Yes adding keywords for layers will be helpful in future. Regarding http://159.87.39.4/dataset/michigan-well-log-observation-data dataset, I was just exploring metadata for WellLog Model to understand how to distinguish it from other models.

**Comment by dan-olaru-reisys** [comment]
@ccaudill There are two source types that the harverster can accept: CSW Server & NGDS CSW Server
https://www.dropbox.com/s/lii1xj1sxgsjkzg/Screenshot%202015-03-11%2015.55.51.png?dl=0

For this task, do we need to worry about both of them or just the "NGDS CSW Server" source type?

Also, we'd like to find out what the difference is between these two Harvester Source types.

**Comment by ccaudill** [comment]
Thanks @dan-olaru-reisys This does need to function with both harvest types. I'll add @smrazgs if he wants to comment.

**Comment by ccaudill** [comment]
@ydave-reisys Here is a current list of the content model keywords:
https://github.com/ngds/documents/wiki/usgincm:-Content-Model-Keywords-List#list-of-content-models-with-usgincm-prefix
@jessica-azgs Steve and I were thinking that usginmodelsAPI could be modified so that these keywords could be accessed by calling a content model URI?

**Comment by jessica-azgs** [comment]
@ccaudill Yes, the usginmodels API could be modified. They could be hardcoded like [def get_service_names():](https://github.com/usgin/usginmodels/blob/master/usginmodels/data.py#L1) though this (or `def get_service_names():` for that matter) is not a good long term solution. Ultimatedly the list should not be hardcoded.

**Comment by ccaudill** [comment]
Would it be possible for us to be able to harvest in an Excel file (with the same keywords) and convert that to CSV file before it goes to be published for tier 3 services through GeoServer?  GDR says that it is not good policy for them to do a conversion from Excel to CSV, as the data providers will be giving them data in Excel format. Could you let us know if you think it is possible to have this functionality also upon harvest?
@smrazgs  @dan-olaru-reisys

**Comment by ydave-reisys** [comment]
@ccaudill Is usginmodels api updated to include a look-up for the keywords based on the content model?

**Comment by dan-olaru-reisys** [comment]
@ccaudill can you provide us with a sample Excel file from GDR?

**Comment by ccaudill** [comment]
@ydave-reisys usginmodels api has not been updated yet - I was speaking with @FuhuXia (I believe) on the project call yesterday, and he was going to make a branch of https://github.com/usgin/usginmodels to make some changes there. Is the keyword call functionality that you can change in that branch at the same time? 
Note as Jessica said earlier " Yes, the usginmodels API could be modified. They could be hardcoded like def get_service_names(): though this (or def get_service_names(): for that matter) is not a good long term solution. Ultimatedly the list should not be hardcoded."
We have not had the manpower to work on this yet, if this is the best solution. We can put them at an online location. http://schemas.usgin.org/models/ would be the best place, but we don't have a Django expert in-house anymore that can add them there.

**Comment by smrazgs** [comment]
@ccaudill is mostly off line this week, and I'm trying to catch up. Where do we stand on this one?
I created a table with the feature/layer names for WFS/WMS, namespace URI, and USGIN keyword for to flag tier 3 data; its at https://github.com/usgin-models/exchangecatalog/blob/master/keywordsNamespacesContentModel.csv
We also created a test Excel workbook with named cells in A1, A2, A3 of sheet one containing:
A1 (named 'typeLayerName') contains the name for WMS layer or WFS featureType deployed with this data; 
A2 (named usginKeyword) contains the keyword to place in the metadata keyword to flag this as a tier3 dataset
A3 (named dataTab) contains the name of the tab containing the data for this tier3 dataset.

This is workable for template workbooks that support only one layer/featureType. The chemistry templates have multiple tabs for different layer/featureTypes. We need to work out convention for how to deal with those.  That will be opened as a separate issue.

**Comment by ccaudill** [comment]
Can we please update this issue, as this seems to be fixed? @dan-olaru-reisys @ydave-reisys Please provide some brief information about specifically what you've done and what you see working now, with some links if possible. Thank you

**Comment by ydave-reisys** [comment]
@ccaudill : I am able to harvest dataset with Tier 3 CSV files and validate them against models selected based on keywords mentioned in metadata. I am currently working on saving csv file with corrected data. Pending task is publishing resource to OGC.

Attached is screenshot of finished harvest jobs with errors.
![screen shot 2015-04-14 at 4 09 41 pm](https://cloud.githubusercontent.com/assets/3017376/7146337/d9592dfc-e2c0-11e4-9f37-b6a82e26d91d.png)

**Comment by ccaudill** [comment]
I know we just talked about this earlier (sorry), but thanks for putting it in writing here.

There was some brief discussion about the possibility of automatically converting files uploaded as Excel to CSV format before they are published. If we put text in a known field of a known tab of the Excel spreadsheet (which indicated the content model type and the layer), could we add in this functionality into this process? This is a pretty big desire from our client. Here's a start at what additional text would be added to the Excel files, which could call usginmodelsAPI:

![cm-keywords](https://cloud.githubusercontent.com/assets/3188489/7146555/42b218b2-e2a9-11e4-97ee-7c601ee4894d.JPG)

**Comment by ydave-reisys** [comment]
@ccaudill The approach we have decided on for handling CSV files with minor errors is that we will not alter resource or csv file during harvesting process. We will upload corrected CSV file to datastore instead of original.

**Comment by ccaudill** [comment]
Sure thing. The messages given should be enough for the user, and next best thing to giving them a corrected file. Let's go with it. @dan-olaru-reisys was looking into the Excel file example that I gave him, exploring whether or not a tier 3 Excel data file could be converted to CSV file for GeoServer publication during a harvest process.

**Comment by ccaudill** [comment]
This should be completed and already in the new rpm. We need to do a test-case on our end, then this issue can be closed.

A separate issue will be made for the automatic Excel - CSV conversion of the dataset (upon harvest and before publishing).

**Comment by ccaudill** [comment]
@dano-reisys I'm doing a test harvest at http://test.geothermaldata.org/harvest/ala/job
which is stuck. I did the recent rpm update yesterday, so the harvest issue should be fixed. The harvest seems to have pulled everything in except the CSV files to publish to services. Could you provide any thoughts? I rebooted after the rpm update. I could kill this, delete the source, and try again. I'm sure this publication shouldn't take long - I've let the harvest run for almost 25 hours.

**Comment by smrazgs** [comment]
This is a long and rambling thread, and I'm going to close it to create a new issue focused on what appears to be the significant problem-- deploying a service from an uploaded CSV file.

**Comment by dano-reisys** [comment]
@ydave-reisys can you please answer Christy's questions.thx

**Comment by ydave-reisys** [comment]
@ccaudill I looked at all datasets in http://services.stategeothermaldata.org/geoAL/csw
which has only 2 datasets with csv files. As per requirement if the dataset confirms to one of Ngds models then only CSV resources are accepted. 
Both datasets Nevada Power Plant Facilities test and Alabama Well Logs test  have xls resource alongwith csv hence both datasets are not harvested.

**Comment by ccaudill** [comment]
@smrazgs Perhaps you should comment on this too, but a valid CSV file should be harvested and published, regardless of what other distributions (file types) are in the harvested metadata.
