### ISSUE TITLE
action.py geothermal_prospector_url not finding the WFS connection information

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-ngds#613]
this is a fork on a specific issue from #580, ref comment https://github.com/ngds/ckanext-ngds/issues/580#issuecomment-86967298; also ref https://github.com/ngds/ckanext-ngds/issues/580#issuecomment-86580998
```
get_action('resource_search')(context, {'query': 'parent_resource:'+search.get('parent_resource', None)})
```
the [XML metadata](http://test.geothermaldata.org/metadata/iso-19139/530f1ee7-9fe5-4ecf-bfb3-af90d099efbd.xml) for Vermont thermal conductivity does not have a gmd:protocol value in the WMS and WFS distribution CI_OnlineResources.
the code for geothermal_prospectory_url looks for a protocol value = OCC:WFS ("WFSResource.get('protocol', None) == 'OGC:WFS'"). The fix suggested in comment https://github.com/ngds/ckanext-ngds/issues/580#issuecomment-86580998 applies here.

**Comment by smrazgs** [comment]
additional information added in original issue posting

**Comment by smrazgs** [comment]
something like WFSResource.get('url',None) contains 'service=WFS'....

**Comment by dan-olaru-reisys** [comment]
@smrazgs 

We have to issues here i think:
Before I can get to WFSResource.get('url',None), I need WFSResource dictionary.

The problem is that 
`get_action('resource_search')(context, {'query': 'parent_resource:'+search.get('parent_resource', None)})`
doesn't return anything because the WMS resource lacks `parent_resource`
One fix would be to get the dataset_id based on the resource_id of the WMS and then loop over all dataset resources until we find the one that has the format = wfs. That's why i asked weather a dataset could have multiple wfs resources (if yes, do we include all of them in the geothermal prospector link?)

**Comment by smrazgs** [comment]
There should only be one WFS corresponding to each WMS, but there's technically no reason why a dataset can't have multiple WMS and WFS distributions.  Its safe to assume that the first WFS you find associated with the dataset that has the WMS can be used in the prospector URL.  Only one WMS and WFS should be in the prospector call. 

Does anything in the CKAN catalog have a parent_resource?  That key isn't in my list of stuff in the CKAN package JSON.

**Comment by dan-olaru-reisys** [comment]
@smrazgs tire3 datasets have that.

http://uat-ngds.reisys.com/api/3/action/resource_search?query=format:wms

**Comment by smrazgs** [comment]
Seems like going back to the dataset (CKAN package???) that contains the WMS resource and looking for a WFS resource is exactly what needs to be done.

**Comment by dan-olaru-reisys** [comment]
@smrazgs yes, that's what i mean here, i think we are on the same page:
> One fix would be to get the dataset_id based on the resource_id of the WMS and then loop over all dataset resources until we find the one that has the format = wfs.

**Comment by smrazgs** [comment]
I ran a search for http://uat-ngds.reisys.com/api/3/action/resource_search?query=format:wfs
 (878 results), then picked a "resource_group_id" (04902d02-606c-482a-9462-00129927e6af) and looked for that GUID in the format:wms results and found the WMS that goes with the WFS (WIWellHeaders).

so it looks like the WFSresource search should be something along the lines of 
```
get_action('resource_search')(context, {'query': 'resource_group_id:'+search.get('resource_group_id', None)})
```
instead of parent_resource

**Comment by dan-olaru-reisys** [comment]
@smrazgs that query will not work with ckan,
the only way i found this to work is:

`SELECT resource_group.package_id
 FROM resource, resource_group
WHERE resource.id='<resource_id>' AND resource.resource_group_id=resource_group.id'''`

**Comment by dan-olaru-reisys** [comment]
Seems to be working now after a code fix:

http://uat-ngds.reisys.com/dataset/tier3-welllog
http://uat-ngds.reisys.com/dataset/alaska-thermal-springs2

**Comment by dan-olaru-reisys** [comment]
@ccaudill I spoke to @JihadMotii-REISys and he said that he was never aware of this feature.
@smrazgs you said there is something that NREL needs to fix on their end, could this be related?
