### ISSUE TITLE
 Data Download not available in Geothermal Prospector

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#616]
https://github.com/ngds/ckanext-ngds/issues/613

...when clicking the down arrow for data download in GeoProsp. Shouldn't this come from the WFS?

@dan-olaru-reisys

**Comment by ccaudill** [comment]
From Dan Getmans:


We currently disable this functionality for external layers for a number of reasons. The main one being that it is a server killer if the data provider has not disabled it on large datasets, which is common.

We could provide a link back to NGDS in the dialog so that users could download the data there if it was available, but I would need to think over the tasking for that on our end. What do you think about sending another parameter called NGDS_ID that we could use to provide a link back to the data?

**Comment by ccaudill** [comment]
From Dan Olaru: Dan, I don¹t see any issues in adding another parameter on our end.
Could you please give us more information on the ³dialog" you mentioned in your email (I am trying to get a better understanding on how you would provide the link back to us)
@dan-olaru-reisys

**Comment by smrazgs** [comment]
This looks to me like something that should be handled on the prospector side. Make a request to the feature service to get the count of features, then alert user if the number is big. Same way its handled in the existing USGIN data explorer that Jessica built.

**Comment by smrazgs** [comment]
This function has been disabled on Prospector side. Close issue
