### ISSUE TITLE
Editing a record (manage button) causes duplicates in search results

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-ngds#617]
I edited a couple of Alabama metadata records 
http://final.geothermaldata.org/dataset/heat-flow-in-the-gulf-coastal-plain7067a
http://final.geothermaldata.org/dataset/geothermal-conditions-and-their-implications-for-basement-tectonics-in-the-gulf-coast-margin
and now they show up twice in the search results.

**Comment by smrgeoinfo** [comment]
Problem will be clearer as we work on the editor (#635)

**Comment by GaryHudmanAZGS** [comment]
Corrected the create new and update process to correctly.
