### ISSUE TITLE
Need a user-friendly way to gracefully handle stuck harvests

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#620]
What should be done when a harvest looks to be completed, but is stuck on "Running"? 
http://final.geothermaldata.org/harvest/smu-geothermal-laboratory/job
@FuhuXia @dano-reisys Thank you!

**Comment by FuhuXia** [comment]
Ah, this infamous stuck issue. The ideal way is to to go thru the log and find out why it is got stuck, either fix code if code error, or fix source if source error. The less ideal way to is to reset the Running status to Finished in the db, so that you can move on with this harvest source. Or, as a last resort, you can clear the job and reharvest.

**Comment by ccaudill** [comment]
Thanks - that's really helpful to know this is just a problem seen in CKAN. As most nodes will be just doing a clear and reharvest, I'll try that (also, it sounds more doable).

**Comment by ccaudill** [comment]
Hmm, it harvested on it's own after days... weird.

**Comment by smrazgs** [comment]
Perhaps a button that will execute the necessary bail out/clean up process and hopefully report status to the user-- did anything harvest, what should they do next....

**Comment by ccaudill** [comment]
@FuhuXia Could you give a simple command to kill a process? I don't know where it is (in gather or harvest) but it looks complete - except that it keeps a "Running" status. 
I don't see people being able to troubleshoot this, if it's a common problem. Could we have a button to kill a harvest?

**Comment by ccaudill** [comment]
So deleting the harvest source completely seems to solve the problem - it works in a matter of seconds. If a button to kill is not possible, we can endeavor to make those who will have nodes aware that this is a persistent CKAN problem.

**Comment by dano-reisys** [comment]
@FuhuXia  is saying that the Clear button should stop the harvesting job (same goes for deleting the harvester source)

**Comment by ccaudill** [comment]
So the same harvest stopped at the same place (still indicates Running). Could you provide me with some commands to run to investigate, which I'll also put on the Readme for others who run into the same problem. Alao the commands to indicate "Finished" might be helpful. Thanks!

**Comment by ccaudill** [comment]
@FuhuXia @dano-reisys Could you please provide us with some text as indicated in the above comment?

**Comment by ccaudill** [comment]
Now, all harvests that I'm running at http://search.geothermaldata.org/harvest are never finishing but always say "Running".  I don't know how to fix what is going on, because there's no way to really know. Deleting and restarting a harvest source seems to get the same result. Could you perhaps connect to the server remotely and help us out? @dano-reisys @FuhuXia

**Comment by FuhuXia** [comment]
It is caused by a recent change in ckanext-spatial extension. we will fix it.

**Comment by ccaudill** [comment]
Oh thank goodness!  I am SOOOO glad to hear it!  Many, many thanks Fuhu. Please keep me updated about when we can do the update!

**Comment by ccaudill** [comment]
per Dan: "christy, I was able to harvest from http://igs.indiana.edu/geoportal/csw following fuhu/yaditi's fix
[5/12/2015 3:24:55 PM] Dan Olaru: I will have the new rpm ready for you tomorrow"

**Comment by ccaudill** [comment]
new rpm ready (ngds.ckan-2.2-313.x86_64.rpm ).  We just need to update and test.

**Comment by ccaudill** [comment]
Harvest finished! Thanks @dano-reisys
