### ISSUE TITLE
Edit UI doesn't show bounding box coordinates

### ISSUE THREAD

**Issue by smrazgs** [ngds/ckanext-ngds#622]
e.g. http://search.geothermaldata.org/dataset/iowa-bedrock-geology
bounding box shows up in the details section, but if you log in and click on manage, open the geographic extent section of the editor, the fields for the bbox coordinates are empty.

**Comment by smrgeoinfo** [comment]
back burner, should get fixed in editor overhaul (see #635)

**Comment by GaryHudmanAZGS** [comment]
Created new custom widget.
