### ISSUE TITLE
PDFs not previewing

### ISSUE THREAD

**Issue by ccaudill** [ngds/ckanext-ngds#631]
http://search.geothermaldata.org/dataset/geothermal-opportunities-in-nevada/resource/bb0245d7-a4ed-464a-8822-e368baf52bbf

Download works though

**Comment by GaryHudmanAZGS** [comment]
Hi,
I have changed the max PDF size to 50 MB and it seems to clear up the issue. Are there any other PDF issues other than size ? Else I think this is solved.
